/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bcwellnesdesktop.View;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author marku
 */
public class CounselorInput extends javax.swing.JFrame {
    public JTextField txtName;
    public JTextField txtSpecialization;
    public JComboBox<String> cmbAvailability;
    public JButton btnSave;
    /**
     * Creates new form CounselorInput
     */
    public CounselorInput() {
        setTitle("Counselor Form");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setLayout(new GridBagLayout());
        getContentPane().setBackground(new Color(60, 63, 65));
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        Font font = new Font("Segoe UI", Font.PLAIN, 14);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 20, 10, 20);

        JLabel lblName = createLabel("Name:", font);
        txtName = createTextField(font);

        JLabel lblSpec = createLabel("Specialization:", font);
        txtSpecialization = createTextField(font);

        JLabel lblAvail = createLabel("Availability:", font);
        cmbAvailability = new JComboBox<>(new String[]{"Available", "Unavailable"});
        styleCombo(cmbAvailability, font);

        btnSave = createStyledButton("Save");

        gbc.gridy = 0;
        addRow(lblName, txtName, gbc);
        addRow(lblSpec, txtSpecialization, gbc);
        addRow(lblAvail, cmbAvailability, gbc);

        gbc.gridy++;
        gbc.gridwidth = 2;
        add(btnSave, gbc);
    }
    private JLabel createLabel(String text, Font font) {
        JLabel lbl = new JLabel(text);
        lbl.setForeground(Color.WHITE);
        lbl.setFont(font);
        return lbl;
    }

    private JTextField createTextField(Font font) {
        JTextField tf = new JTextField();
        tf.setFont(font);
        return tf;
    }

    private void styleCombo(JComboBox<?> combo, Font font) {
        combo.setFont(font);
        combo.setBackground(new Color(100, 100, 100));
        combo.setForeground(Color.WHITE);
    }

    private JButton createStyledButton(String text) {
        JButton button = new JButton(text);
        button.setBackground(new Color(100, 100, 100));
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        button.setBorder(BorderFactory.createEmptyBorder(8, 16, 8, 16));
        return button;
    }

    private void addRow(Component label, Component field, GridBagConstraints gbc) {
        gbc.gridx = 0;
        add(label, gbc);
        gbc.gridx = 1;
        add(field, gbc);
        gbc.gridy++;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
