/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bcwellnesdesktop.View;
import bcwellnesdesktop.Controller.ApointmentController;
import bcwellnesdesktop.DBConnection;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author marku
 */
public class DashboardFrame extends javax.swing.JFrame {
   private JButton btnAppointments;
    private JButton btnCounselors;
    private JButton btnFeedback;
    private JButton btnExit;

    private JPanel mainPanel;
    private JPanel contentPanel;
    private CardLayout cardLayout;

    private AppointmentPanel appointmentsPanel;
    private CounselorPanel counselorsPanel;
    private FeedbackPanel feedbackPanel;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
       setTitle("BC Wellness Management System - Dashboard");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        Color backgroundColor = new Color(45, 45, 45);
        Color buttonColor = new Color(70, 70, 70);
        Color textColor = Color.WHITE;

        setLayout(new BorderLayout());

        mainPanel = new JPanel();
        mainPanel.setBackground(backgroundColor);
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));

        btnAppointments = new JButton("Appointments");
        styleButton(btnAppointments, buttonColor, textColor);
        btnCounselors = new JButton("Counselors");
        styleButton(btnCounselors, buttonColor, textColor);
        btnFeedback = new JButton("Feedback");
        styleButton(btnFeedback, buttonColor, textColor);
        btnExit = new JButton("Exit");
        styleButton(btnExit, new Color(120, 20, 20), textColor);

        mainPanel.add(btnAppointments);
        mainPanel.add(btnCounselors);
        mainPanel.add(btnFeedback);
        mainPanel.add(btnExit);

        add(mainPanel, BorderLayout.NORTH);

        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        appointmentsPanel = new AppointmentPanel();
        counselorsPanel = new CounselorPanel();
        feedbackPanel = new FeedbackPanel();

        contentPanel.add(createWelcomePanel(), "HOME");
        contentPanel.add(appointmentsPanel, "APPOINTMENTS");
        contentPanel.add(counselorsPanel, "COUNSELORS");
        contentPanel.add(feedbackPanel, "FEEDBACK");

        add(contentPanel, BorderLayout.CENTER);

        btnExit.addActionListener(e -> System.exit(0));
        btnAppointments.addActionListener(e -> cardLayout.show(contentPanel, "APPOINTMENTS"));
        btnCounselors.addActionListener(e -> cardLayout.show(contentPanel, "COUNSELORS"));
        btnFeedback.addActionListener(e -> cardLayout.show(contentPanel, "FEEDBACK"));
    }
     private void styleButton(JButton button, Color bgColor, Color fgColor) {
        button.setBackground(bgColor);
        button.setForeground(fgColor);
        button.setFocusPainted(false);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
    }

    private JPanel createWelcomePanel() {
        JPanel panel = new JPanel();
        panel.setBackground(new Color(60, 63, 65));
        panel.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridx = 0;
        gbc.anchor = GridBagConstraints.CENTER;

        JLabel titleLabel = new JLabel("BC Wellness Management System");
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        gbc.gridy = 0;
        panel.add(titleLabel, gbc);

        JLabel subtitleLabel = new JLabel("Welcome! Please select an option above to begin.");
        subtitleLabel.setForeground(Color.LIGHT_GRAY);
        subtitleLabel.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        gbc.gridy = 1;
        panel.add(subtitleLabel, gbc);

        return panel;
    }
    public static DBConnection db = new DBConnection();
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new DashboardFrame().setVisible(true));
        try{
            db.connect();
        }catch(ClassNotFoundException ex){
            ex.printStackTrace();
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
